### PR TITLE
Create PIDfile before parent exits for systemd

### PR DESCRIPTION
**Pull request by stuart12**
Systemd reads the PID file as soon as the parent exits so we
should create the PID file in the parent before exiting.

### CODE REVIEW

**Comment by badaix** [comment]
unfortunately this conflicts with the current master. What is the recommended strategy to solve this?
I could manually merge your changes, but this would not link to your contribution.
Can you redo the patch on the current master?

**Comment by badaix** [comment]
BTW: I think the official systemd way would be not to fork at all, i.e. not to start as a daemon. But for the moment I would clearly prefer your patch.

**Comment by stuart12** [comment]
I think that forking is a correct way to write a unit. If we use "simple" we need a find a different way to tell systemd that the daemon is ready. See the [systemd doc](https://www.freedesktop.org/software/systemd/man/systemd.service.html). I will try to rebase this weekend.

**Comment by badaix** [comment]
Thanks!

**Pull request merged**
