### PR TITLE
new style resolver and connect - fixes build with boost 1.87.0

### LINKED ISSUE #1307: future deprecated query from boost
- https://stackoverflow.com/questions/50553681/what-replaced-asiotcpresolverquery
- https://stackoverflow.com/questions/57434699/boost-asio-open-socket-without-using-deprecated-methods

Can be triggered by compiling with `CXXFLAGS+=" -DBOOST_ASIO_NO_DEPRECATED"`

https://github.com/badaix/snapcast/blob/f6ce4f3fbb3c797f5d92578d7bc8df547ad4cd64/client/client_connection.cpp#L127

https://github.com/badaix/snapcast/blob/f6ce4f3fbb3c797f5d92578d7bc8df547ad4cd64/client/client_connection.cpp#L130

```
[2/7] Building CXX object client/CMakeFiles/snapclient.dir/client_connection.cpp.o
FAILED: client/CMakeFiles/snapclient.dir/client_connection.cpp.o
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ -DBOOST_ASIO_NO_TS_EXECUTORS -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_ALSA -DHAS_AVAHI -DHAS_DAEMON -DHAS_EXPAT -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_PULSE -DHAS_SOXR -DHAS_VORBIS -DHAS_VORBIS_ENC -DVERSION=\"0.29.0\" -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/snapcast-0.29.0 -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/snapcast-0.29.0/include -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/snapcast-0.29.0/client -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/dbus-1.0 -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/dbus-1.0/include -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/opus -march=x86-64-v3 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -pthread -DBOOST_ASIO_NO_DEPRECATED                      -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/aixlog-1.5.0/usr/include                       -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/asio-1.31.0/usr/include                       -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/install_pkg/popl-1.3.0/usr/include -std=gnu++17 -Wall -Wextra -pedantic -Wno-unused-function -MD -MT client/CMakeFiles/snapclient.dir/client_connection.cpp.o -MF client/CMakeFiles/snapclient.dir/client_connection.cpp.o.d -o client/CMakeFiles/snapclient.dir/client_connection.cpp.o -c /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/build/snapcast-0.29.0/client/client_connection.cpp
../client/client_connection.cpp: In member function 'void ClientConnection::connect(const ResultHandler&)':
../client/client_connection.cpp:127:20: error: 'query' is not a member of 'boost::asio::ip::tcp::resolver' {aka 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>'}
  127 |     tcp::resolver::query query(server_.host, cpt::to_string(server_.port), boost::asio::ip::resolver_query_base::numeric_service);
      |                    ^~~~~
../client/client_connection.cpp:130:39: error: 'query' was not declared in this scope
  130 |     auto iterator = resolver_.resolve(query, ec);
      |                                       ^~~~~
../client/client_connection.cpp:130:39: note: suggested alternatives:
In file included from /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/asio/execution/blocking.hpp:23,
                 from /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/asio/execution/any_executor.hpp:31,
                 from /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/asio/execution.hpp:19,
                 from /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/asio/any_io_executor.hpp:22,
                 from ../client/client_connection.hpp:28,
                 from ../client/client_connection.cpp:20:
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/asio/query.hpp:114:6: note:   'boost_asio_query_fn::query'
  114 | void query();
      |      ^~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/asio/query.hpp:263:3: note:   'boost::asio::{anonymous}::query'
  263 |   query = boost_asio_query_fn::static_instance<>::instance;
      |   ^~~~~
```

### PR DESCRIPTION
**Pull request by heitbaum**
- closes #1307
- additionally cleans up warnings
  - [call v1 boost headers fixing deprecated warning](https://github.com/badaix/snapcast/commit/431adc09670b47ed7dbdf0f0ed8c633a08ce4022)

### CODE REVIEW

**Comment by badaix** [comment]
Thanks, unfortunately it doesn't compile with boost < 1.87.0. 
I fixed it with less changes 6190041

**Comment by heitbaum** [comment]
> Thanks, unfortunately it doesn't compile with boost < 1.87.0. I fixed it with less changes [6190041](https://github.com/badaix/snapcast/commit/6190041e863968d76b6d16140bba90be6dff848f)

Looks good. Works here. Only the warning remain.
```
In file included from /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/config/header_deprecated.hpp:18,
                 from /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/process/args.hpp:7,
                 from ../client/player/player.cpp:37:
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/process/args.hpp:8:1: note: '#pragma message: This header is deprecated. Use <boost/process/v1/args.hpp> instead.'
    8 | BOOST_HEADER_DEPRECATED("<boost/process/v1/args.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/process/async.hpp:8:1: note: '#pragma message: This header is deprecated. Use <boost/process/v1/async.hpp> instead.'
    8 | BOOST_HEADER_DEPRECATED("<boost/process/v1/async.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/process/child.hpp:8:1: note: '#pragma message: This header is deprecated. Use <boost/process/v1/child.hpp> instead.'
    8 | BOOST_HEADER_DEPRECATED("<boost/process/v1/child.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-13.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/process/exe.hpp:8:1: note: '#pragma message: This header is deprecated. Use <boost/process/v1/exe.hpp> instead.'
    8 | BOOST_HEADER_DEPRECATED("<boost/process/v1/exe.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by badaix** [comment]
Yes, this process stuff needs some special attention, using v1 for older boost versions and v2 for more recent versions, both versions have plenty of warnings, I think Snapcast needs some encapsulated process class, to not spread this boost process stuff on several places in the code base.

According to the [changelog](https://www.boost.org/users/history/version_1_87_0.html) boost process v1 will be removed in the next boost version:

```
Process:
...
(v1) Added deprecation notice for 1.88.
```

Currently Snapcast requires boost version >= 1.74.0 and I will try to keep it compatible with older boost versions, because the boost version that is shipped in "stable" Linux distributions is usually a few versions behind.

**Comment by heitbaum** [comment]
> Yes, this process stuff needs some special attention, using v1 for older boost versions and v2 for more recent versions, both versions have plenty of warnings, I think Snapcast needs some encapsulated process class, to not spread this boost process stuff on several places in the code base.
> 
> According to the [changelog](https://www.boost.org/users/history/version_1_87_0.html) boost process v1 will be removed in the next boost version:
> 
> ```
> Process:
> ...
> (v1) Added deprecation notice for 1.88.
> ```
> 
> Currently Snapcast requires boost version >= 1.74.0 and I will try to keep it compatible with older boost versions, because the boost version that is shipped in "stable" Linux distributions is usually a few versions behind.

Likely we (LibreELEC) will go with 1.87.0 with LE13 in Q1 next year. So probably fine for the present. I’ll keep our dev tree up to current after LE13 is released - so we will see what 1.88+ brings — plus is that we have been able to identify these and close som3 already 👍

**Pull request closed without merging**
