### PR TITLE
cmake: fix CheckAtomic module to avoid "undefined reference to `__atomic_store_8'" on some architectures (#490)

### LINKED ISSUE #490: armv6l: undefined reference to `__atomic_store_8'
Attempting to build Snapcast 0.16.0 on Void Linux armv6l results in the following error:
```
[ 64%] Building CXX object client/CMakeFiles/snapclient.dir/decoder/pcm_decoder.cpp.o
[ 71%] Building CXX object client/CMakeFiles/snapclient.dir/player/player.cpp.o
[ 78%] Building CXX object client/CMakeFiles/snapclient.dir/player/alsa_player.cpp.o
[ 85%] Building CXX object client/CMakeFiles/snapclient.dir/decoder/ogg_decoder.cpp.o
[ 92%] Building CXX object client/CMakeFiles/snapclient.dir/decoder/flac_decoder.cpp.o
[100%] Linking CXX executable ../../bin/snapclient
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: CMakeFiles/snapclient.dir/controller.cpp.o: in function `Controller::worker()':
controller.cpp:(.text+0x25c0): undefined reference to `__atomic_load_8'
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: CMakeFiles/snapclient.dir/stream.cpp.o: in function `Stream::getPlayerChunk(void*, std::chrono::duration<long long, std::ratio<1ll, 1000000ll> > const&, unsigned long)':
stream.cpp:(.text+0x2e78): undefined reference to `__atomic_load_8'
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: stream.cpp:(.text+0x321c): undefined reference to `__atomic_load_8'
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: stream.cpp:(.text+0x433c): undefined reference to `__atomic_load_8'
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: stream.cpp:(.text+0x53c8): undefined reference to `__atomic_load_8'
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: CMakeFiles/snapclient.dir/time_provider.cpp.o: in function `TimeProvider::setDiffToServer(double)':
time_provider.cpp:(.text+0xb20): undefined reference to `__atomic_store_8'
/usr/lib/gcc/arm-linux-gnueabihf/9.2.0/../../../../arm-linux-gnueabihf/bin/ld: time_provider.cpp:(.text+0xed0): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [client/CMakeFiles/snapclient.dir/build.make:220: ../bin/snapclient] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: client/CMakeFiles/snapclient.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
The complete build log is available on the Void Linux CI: https://travis-ci.org/void-linux/void-packages/builds/602121587

### PR DESCRIPTION
**Pull request by xabolcs**
Tested with the following toolchains with OpenWrt:
* toolchain-aarch64_cortex-a72_gcc-8.3.0_musl
* toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.3.0_musl_eabi
* toolchain-i386_pentium_gcc-8.3.0_musl
* toolchain-mips_24kc_gcc-8.3.0_musl
* toolchain-mipsel_24kc_gcc-8.3.0_musl

And also [was successfully tested](https://github.com/badaix/snapcast/issues/490#issuecomment-548992734) on `armv6l`.

Fix #490

### CODE REVIEW

**Comment by badaix** [comment]
is this new line `set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")`
right after this line `list(APPEND CMAKE_REQUIRED_LIBRARIES "atomic")` required? 
At least both commands are intended to do the same thing, so one of them should be superfluous

**Comment by xabolcs** [comment]
That `list` command wasn't working on tested architectures (ie. still got the "undefined reference to `__atomic_store_8'" error in the linking stage).

Never tried to remove.

**Comment by xabolcs** [comment]
I'm CMake newbie, and will check the remove of `list(APPEND ...` line

**Comment by xabolcs** [comment]
>  At least both commands are intended to do the same thing, so one of them should be superfluous

Removed the `list(APPEND CMAKE_REQUIRED_LIBRARIES "atomic")` lines.

**Comment by xabolcs** [comment]
> Removed the `list(APPEND CMAKE_REQUIRED_LIBRARIES "atomic")` lines.

Ohh ... I was test something other, as this errors out:
```
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Failed
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - not found
-- Performing Test HAVE_LIBATOMIC_2ARGS
-- Performing Test HAVE_LIBATOMIC_2ARGS - Failed
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Failed
-- Looking for __atomic_load_8 in atomic
-- Looking for __atomic_load_8 in atomic - not found
-- Performing Test HAVE_CXX_LIBATOMICS64_2ARGS
-- Performing Test HAVE_CXX_LIBATOMICS64_2ARGS - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITH_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITH_LIB - Failed
CMake Error at cmake/CheckAtomic.cmake:141 (message):
  Host compiler must support std::atomic!
Call Stack (most recent call first):
  CMakeLists.txt:80 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by badaix** [comment]
was this working with both lines in (as in your PR)?

**Comment by xabolcs** [comment]
> was this working with both lines in (as in your PR)?

Sorry for the late response!

Yes, that (b5f969852d4f5ac2160f08e24ffa87faaa13adcd) was the only valid state:
* `list(APPEND ...)` without `set(...` (up to commit 6f794145882499ed1350e24931aebf5e24b71416) it died at linking stage
* `set(...` without `list(APPEND ...)` (up to commit 20800d0f91023392ddd2bd6ee8fc936d03cc480e) it died at configuring stage


Thanks for accepting! :+1:

**Comment by badaix** [comment]
Thanks for your effort!

**Pull request merged**
