### PR TITLE
Small documentation corrections

### PR DESCRIPTION
**Pull request by jwillikers**
This PR fixes small typos in the documentation and adds missing build dependencies necessary for building on Fedora.
This PR also adds the `host` option to the Mopidy configuration examples when using the TCP source.
Without `host=127.0.0.1` I wasn't able to get the examples to work.

Some small improvements were made to the ALSA backend configuration examples.
The ALSA loopback device is now referred to by name instead of index since the index is subject to change.

* * *

## Pull Request Checklist

* Contributions must be licensed under the [GPL-3.0 License](LICENSE)

* This project loosely follows the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html)

* For better compatibility with embedded toolchains, the used C++ standard should be limited to C++14

* Code should be formatted by running `make reformat`

* Branch from the `develop` branch and ensure it is up to date with the current `develop` branch before submitting your pull request. If it doesn't merge cleanly with `develop`, you may be asked to resolve the conflicts. Pull requests to master will be closed.

* Commits should be as small as possible while ensuring that each commit is correct independently (i.e., each commit should compile and pass tests).

* Pull requests must not contain compiled sources (already set by the default .gitignore) or binary files

* Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests. If tested manually, provide information about the test scope in the PR description (e.g. “Test passed: Upgrade version from 0.42 to 0.42.23.”).

* Create _Work In Progress [WIP]_ pull requests only if you need clarification or an explicit review before you can continue your work item.

* If your patch is not getting reviewed or you need a specific person to review it, you can @-reply a reviewer asking for a review in the pull request or a comment, or you can ask for a review by contacting us via [email](mailto:snapcast@badaix.de).

* Post review:
  * If a review requires you to change your commit(s), please test the changes again.
  * Amend the affected commit(s) and force push onto your branch.
  * Set respective comments in your GitHub review to resolved.
  * Create a general PR comment to notify the reviewers that your amendments are ready for another round of review.

### CODE REVIEW

**Comment by kingosticks** [comment]
Surprised you need the `host` argument as the default is "localhost".

**Comment by jwillikers** [comment]
> Surprised you need the `host` argument as the default is "localhost".

Me too, but apparently I'm not the only one: https://github.com/badaix/snapcast/issues/511#issuecomment-570056242

**Comment by badaix** [comment]
Thanks!

**Comment by kingosticks** [comment]
> Does localhost use IPv6 instead of IPv4 in GStreamer or something?

Sorry for the slow response. I don't think this is specific to GStreamer (which will surely be using the system resolver). Seems that on dual-stack systems, IPv6 is preferred over v4 and since localhost resolves to both 127.0.01 and ::1, the latter wins. I can see the same thing when I `ping localhost` on my machine.

Presumably listening/connecting on ::1 is fine providing that matches the other side. But if snapserver.conf is explicitly using 127.0.0.1 (as per the docs, does it even support hostnames?) then Mopidy using ::1isn't going to work. So I think this all makes sense and being explicit on both sides is the correct answer.

**Comment by badaix** [comment]
Just checked the code: the tcp stream doesn't do any host name resolution. Both, IPv4 and IPv6 should work, but no name resolution happens. I will create a feature request for this.

btw: on my Linux Mint machine I have `localhost` for IPv4 and `ip6-localhost` for IPv6:

```shell
 more /etc/hosts
127.0.0.1	localhost
127.0.1.1	Laptop

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Now my IPs are publicly available in the internet, hope I will not get hacked. 
It's Friday :)

**Comment by kingosticks** [comment]
> btw: on my Linux Mint machine I have localhost for IPv4 and ip6-localhost for IPv6:

I have the same for my Ubuntu 20.04 machine. But my Fedora 33 and Raspbian systems have something more futuristic:
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```
I'm now going to turn my machines off to avoid the hacker onslaught.

**Comment by badaix** [comment]
First the hacker has to resolve the IP conflict between your and my IP addresses

**Comment by jwillikers** [comment]
Fedora 35:

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain
```

**Pull request merged**
