### PR TITLE
Advertise the webapp

### PR DESCRIPTION
**Pull request by atoomic**
Add a sentence to the markdown to advertise the new web app to control all clients connected to a snapcast server. 

The app is still in progress, but very usable and responsive on mobile devices.

### CODE REVIEW

**Comment by badaix** [comment]
Hi @atoomic, @happyleavesaoc, @unimatrix27 
please note that I've changed the JSON RPC API to support Groups in release 0.11.0.
It is still poorly [documented](https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md). 
The Android App might serve as some kind of "reference" client.
I will focus on bugfixes and maybe release another beta pre-release before the final 0.11.0 release. So it would be a good moment to adapt to the RPC API changes.

BR,
Johannes

**Comment by unimatrix27** [comment]
Thanks for the heads up. Ill adapt the FHEM module as soon as I find the time. Documentation is not an issue for me. I just use the APP and watch network traffic with tcpflow. Pretty straightforward.

**Comment by atoomic** [comment]
Thanks @badaix for the update, the recent update to the JSON RPC API in 0.11 are the reasons why we have two branches in the webapp ui. Currently master tracks the development and is compliant with 0.11 whereas the branch snapcast/v0.10.0 is for the previous version of snapcast.
So technically everything is ready for the release of 0.11.0 but would need to add some informations in the doc and probably branch snapcast/v0.11.0 to make it more clear, then make it the default branch.

**Comment by happyleavesaoc** [comment]
@badaix I'll update the Python API accordingly. Thanks.

**Comment by atoomic** [comment]
@badaix just added some comments and created special branch for v0.11
would perform more tests once released to be sure everything is fine

**Pull request merged**
