### PR TITLE
Update link to the new librespot repository

### PR DESCRIPTION
**Pull request by l3d00m**

### CODE REVIEW

**Comment by Cirromulus** [comment]
Would have saved me a day of trying.

**Comment by badaix** [comment]
thanks!
Sorry, I didn't notice the PR, just Cirromulus comment on it :)

**Comment by Cirromulus** [comment]
No Problem, big thanks for the repo anyway!

**Comment by l3d00m** [comment]
No problem, snapcast is great and very reliable over the last months, thanks to you

**Pull request merged**
